name: reusable cff module

on:
  workflow_call:
    inputs:
      artifact:
        required: true
        description: Artifact to download and commit
        type: string
      branch:
        required: true
        description: Repo branch to use to commit
        type: string
      commit_message:
        required: true
        description: Commit message to use
        type: string
    secrets:
      token:
        required: true
        description: PAT_RELEASE_REPO token

jobs:
  commit_cff:
    name: commit cff
    runs-on: ubuntu-22.04
    steps:
      - name: checkout ${{inputs.branch}}
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        # env:
        #   # load PAT_TOKEN into github token?!?
        #   GITHUB_TOKEN: {{ secrets.PAT_RELEASE_REPO }}
        with:
          ref: ${{inputs.branch}}
          token: ${{secrets.token}}

      - name: download ${{inputs.artifact}}
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact}}

      - name: commit CITATION.cff
        # https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{inputs.commit_message}}
          file_pattern: CITATION.cff
