name: reusable cff update module

on:
  workflow_call:
    inputs:
      version_tag:
        required: true
        description: Version tag to use
        type: string
      branch:
        required: true
        description: Repo branch to use to commit
        type: string
      commit_message:
        required: true
        description: Commit message to use
        type: string

jobs:
  commit_cff:
    name: commit cff from artifact
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{inputs.branch}}
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          ref: ${{inputs.branch}}

      - name: update CITATION.cff
        # use doublequotes to enable variable substitution with bash
        run: |
          echo replace version line
          sed -i -e "s/^version:.*/version: ${{inputs.version_tag}}/" CITATION.cff
          echo replace date
          sed -i -e "s/^date-released:.*/date-released: '$(date +%F)'/" CITATION.cff
          cat CITATION.cff

      - name: commit CITATION.cff
        # https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{inputs.commit_message}}
          file_pattern: CITATION.cff
