name: reusable version module

on:
  workflow_call:
    inputs:
      branch:
        required: true
        description: Repo branch to use to find last tag
        type: string
    outputs:
      version:
        description: Provide last tag as version
        value: ${{jobs.last_tag.outputs.version}}

jobs:
  last_tag:
    name: find last tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.get_version.value}}
    steps:
      - name: checkout ${{inputs.branch}}
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          ref: ${{inputs.branch}}
          # checkout whole history
          fetch-depth: 0
      - name: get version
        id: get_version
        run: |
          git describe --abbrev=0
          echo "::set-output name=value::$(git describe --abbrev=0)"
