# SPDX-FileCopyrightText: 2022 - 2024 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2022 - 2024 Netherlands eScience Center
# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 dv4all
#
# SPDX-License-Identifier: Apache-2.0

name: backend tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend-postgrest/**"
      - "database/**"
      - "backend-tests/**"
  pull_request:
    paths:
      - "backend-postgrest/**"
      - "database/**"
      - "backend-tests/**"

jobs:
  api-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: "backend tests with docker compose"
        working-directory: backend-tests
        run: |
          docker compose up \
            --exit-code-from postgrest-tests
