# SPDX-FileCopyrightText: 2022 Christian Meeßen (GFZ) <christian.meessen@gfz-potsdam.de>
# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences
# SPDX-FileCopyrightText: 2022 dv4all
# SPDX-FileCopyrightText: 2023 - 2024 Dusan Mijatovic (Netherlands eScience Center)
# SPDX-FileCopyrightText: 2023 - 2025 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2023 - 2025 Netherlands eScience Center
#
# SPDX-License-Identifier: Apache-2.0

name: release images

on:
  release:
    types: [published]

  # alternative approach on tag push
  # push:
  #   tags: [ 'v*.*.*' ]

jobs:
  release_tag:
    name: extract version from release tag
    runs-on: ubuntu-22.04
    outputs:
      ref: ${{github.ref}}
      tag: ${{steps.version.outputs.tag}}
    steps:
      - name: output version to tag
        id: version
        run: |
          echo version = ${GITHUB_REF/refs\/tags\//}
          # write value to output
          echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

  log_release_tag:
    needs: release_tag
    name: log version output
    runs-on: ubuntu-22.04
    steps:
      - name: info
        run: |
          echo outputs.ref=${{ needs.release_tag.outputs.ref }}
          echo outputs.tag=${{ needs.release_tag.outputs.tag }}
  auth:
    # it needs to be checked on string value
    if: needs.release_tag.outputs.tag != ''
    needs: [release_tag, log_release_tag]
    name: auth
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/dmijatovic/rsd-saas/auth
      image_tag: ${{needs.release_tag.outputs.tag}}
      service_tag: "v1.6.0-auth"
      dockerfile: authentication/Dockerfile
      docker_context: ./authentication
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  # JUST TEST WITH ONE IMAGE
  database:
    # it needs to be checked on string value
    if: needs.release_tag.outputs.tag != ''
    needs: [release_tag, log_release_tag]
    name: database
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/dmijatovic/rsd-saas/database
      image_tag: ${{needs.release_tag.outputs.tag}}
      service_tag: "v3.0.1-db"
      dockerfile: database/Dockerfile
      docker_context: ./database
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  backend:
    # it needs to be checked on string value
    if: needs.release_tag.outputs.tag != ''
    needs: [release_tag, log_release_tag]
    name: backend api
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/dmijatovic/rsd-saas/backend
      image_tag: ${{needs.release_tag.outputs.tag}}
      service_tag: "v1.13.0-be"
      dockerfile: backend-postgrest/Dockerfile
      docker_context: ./backend-postgrest
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  background-services:
    if: needs.release_tag.outputs.tag != ''
    needs: [release_tag, log_release_tag]
    name: background services
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/dmijatovic/rsd-saas/bg-svc
      image_tag: ${{needs.release_tag.outputs.tag}}
      service_tag: "v1.0.0-bs"
      dockerfile: background-services/Dockerfile
      docker_context: ./background-services
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  frontend:
    # it needs to be checked on string value
    if: needs.release_tag.outputs.tag != ''
    needs: [release_tag, log_release_tag]
    name: frontend
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/dmijatovic/rsd-saas/frontend
      image_tag: ${{needs.release_tag.outputs.tag}}
      service_tag: "v3.3.0-fe"
      dockerfile: frontend/Dockerfile
      docker_context: ./frontend
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  nginx:
    # it needs to be checked on string value
    if: needs.release_tag.outputs.tag != ''
    needs: [release_tag, log_release_tag]
    name: nginx
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/dmijatovic/rsd-saas/nginx
      image_tag: ${{needs.release_tag.outputs.tag}}
      service_tag: "v1.1.4-ng"
      dockerfile: nginx/Dockerfile
      docker_context: ./nginx
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  codemeta:
    # it needs to be checked on string value
    if: needs.release_tag.outputs.tag != ''
    needs: [release_tag, log_release_tag]
    name: codemeta
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/dmijatovic/rsd-saas/codemeta
      image_tag: ${{needs.release_tag.outputs.tag}}
      service_tag: "v1.1.4-cm"
      dockerfile: codemeta/Dockerfile
      docker_context: ./codemeta
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  scrapers:
    # it needs to be checked on string value
    if: needs.release_tag.outputs.tag != ''
    needs: [release_tag, log_release_tag]
    name: scrapers
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/dmijatovic/rsd-saas/scrapers
      image_tag: ${{needs.release_tag.outputs.tag}}
      service_tag: "v1.9.0-sc"
      dockerfile: scrapers/Dockerfile
      docker_context: ./scrapers
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

  documentation:
    # it needs to be checked on string value
    if: needs.release_tag.outputs.tag != ''
    needs: [release_tag, log_release_tag]
    name: documentation
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/dmijatovic/rsd-saas/documentation
      image_tag: ${{needs.release_tag.outputs.tag}}
      service_tag: "${{needs.release_tag.outputs.tag}}-docs"
      dockerfile: documentation/Dockerfile
      docker_context: ./documentation
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}


  # citation:
  #   # it needs to be checked on string value
  #   if: needs.release_tag.outputs.tag != ''
  #   needs: [ release_tag ]
  #   name: citations
  #   uses: ./.github/workflows/_cff.yml
  #   with:
  #     artifact: citation
  #     branch: master
  #     commit_message: "chore(release): update citation file"
  #   secrets:
  #     # need to pass PAT using secrets prop to reusable workflow (module)
  #     # the secrets are not passed automatically to child modules
  #     # see https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow
  #     token: ${{ secrets.PAT_RELEASE_REPO }}


